### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by GZWZC** [54sword/xiaoduyu.com#11]
bash-3.2# npm install
npm WARN addRemoteGit lepture/editor resetting remote /Users/app/.npm/_git-remotes/git-github-com-lepture-editor-git-e9f69459 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/app/.npm/_git-remotes/_templates --mirror git://github.com/lepture/editor.git /Users/app/.npm/_git-remotes/git-github-com-lepture-editor-git-e9f69459: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN addRemoteGit lepture/editor resetting remote /Users/app/.npm/_git-remotes/git-https-github-com-lepture-editor-git-cde57b73 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN deprecated babel-preset-latest@6.24.0: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦
npm ERR! git clone --template=/Users/app/.npm/_git-remotes/_templates --mirror https://github.com/lepture/editor.git /Users/app/.npm/_git-remotes/git-https-github-com-lepture-editor-git-cde57b73: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm WARN addRemoteGit lepture/editor resetting remote /Users/app/.npm/_git-remotes/git-github-com-lepture-editor-git-8a0fa90e because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/app/.npm/_git-remotes/_templates --mirror git@github.com:lepture/editor.git /Users/app/.npm/_git-remotes/git-github-com-lepture-editor-git-8a0fa90e: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/app/.npm/_git-remotes/_templates --mirror git@github.com:lepture/editor.git /Users/app/.npm/_git-remotes/git-github-com-lepture-editor-git-8a0fa90e
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /wzc/小肚鱼/xiaoduyu.com-master/npm-debug.log

osx环境，知道是什么问题吗

**Comment by 54sword** [comment]
看不出问题
请尝试删除 node_modules 文件加，然后重新 npm install 试一试

**Comment by GZWZC** [comment]
@54sword  now is ok, mac osx 10.12 git clone fail
