### ISSUE TITLE
想请问一下你的移动端滚动条效果是怎么做的。我找不到。求教

### ISSUE THREAD

**Issue by miaowwwww** [54sword/xiaoduyu.com#12]

**Comment by 54sword** [comment]
你说的效果，是指记录不同页面的滚动条位置吗？

**Comment by miaowwwww** [comment]
不是。你做的页面，滚动的时候有一个缓冲的效果，然后我并没有看见你使用了transform，想知道你是怎么做的。我自己做的页面，如果要滚动，并没有缓冲效果

**Comment by 54sword** [comment]
我记得没有做这方面的效果哦，滚动条效果都是浏览器自带的

**Comment by miaowwwww** [comment]
那可能是css的问题，我再查查，谢谢你这么快回复。
