### ISSUE TITLE
Error: Cannot find module 'history/lib/createMemoryHistory'

### ISSUE THREAD

**Issue by GZWZC** [54sword/xiaoduyu.com#14]
https://github.com/54sword/xiaoduyu.com/blob/master/server/routes/serverRender.js

import createMemoryHistory from 'history/lib/createMemoryHistory',
Error: Cannot find module 'history/lib/createMemoryHistory'

你好，在这个文件里，为什么要引入createMemoryHistory，我引入后报错，我应该怎么处理

**Comment by 54sword** [comment]
没有找到 history/lib/createMemoryHistory，
请尝试卸载
npm uninstall history 
然后重新安装一下
npm install history
