### ISSUE TITLE
react-router

### ISSUE THREAD

**Issue by cashyu** [54sword/xiaoduyu.com#18]
你好,可以请教一个问题吗? 我自己做的一个小项目,使用的react + react-router + redux + nodejs + express + mongodb,项目可以跑起来,但是刷新页面就会出现404的错误.代码地址https://github.com/cashyu/reactNode,
想请教下,应该怎么处理?

**Comment by 54sword** [comment]
在 index.js 文件，25行上面加入如下代码

```
app.get('*', function (req, res) {
  res.sendFile(path.resolve(__dirname, 'public', 'index.html'))
})
```

将所有的路由都指向 public/index.html 文件，就可以了
