### ISSUE TITLE
页面刷新，样式加载失败

### ISSUE THREAD

**Issue by cmmkj** [54sword/xiaoduyu.com#20]
http://localhost:4000/posts/5910922a7ea7dd7054095cf4　
刷新之后：
![image](https://cloud.githubusercontent.com/assets/20109390/25850267/3ac303ce-34f4-11e7-86ef-8f2788dc980c.png)

**Comment by 54sword** [comment]
发现问题了，请修改  config/index.js 第48行，修改成
```public_path: 'http://localhost:4000',```
再试一试

**Comment by cashyu** [comment]
可以了

**Comment by cashyu** [comment]
为什么我用localhost打开，页面也会有数据，这些数据从哪里来的？

**Comment by 54sword** [comment]
默认我是在 config/index.js，配置了 api 接口，获取的是 xiaoduyu.com 网站的数据
```
api_url: 'https://www.xiaoduyu.com',
api_verstion: 'api/v1',
```
这个API的源代码在 https://github.com/54sword/api.xiaoduyu.com 这里，
你可以在本地启动 api 服务，然后把 api_url 换成你本地的地址就可以了

**Comment by cashyu** [comment]
哦，知道了
