### ISSUE TITLE
你这个是怎么保存登录状态的

### ISSUE THREAD

**Issue by hechuanhua** [54sword/xiaoduyu.com#22]
我看你是吧账号密码加密保存在cookie，然后去解密请求时带的cookie，但是如果是服务端渲染的时候cookie是获取不到的，这个时候你的token值是怎么来的

**Comment by 54sword** [comment]
在服务端可以获取 cookie，也可以在服务端判断 cookie 中的 token 是否有效

**Comment by hechuanhua** [comment]
@54sword 哦，对，应该是服务端渲染的时候会有一次请求首页 ‘/’ 的过程，这个时候可以获取cookie，但是如果是服务端请求API的时候是获取不到cookie的

**Comment by 54sword** [comment]
@hechuanhua 
这里需要注意的是，cookie中token是储存在前端的，而token是通过API登录成功以后获得的，
这个token是由前端自己储存的，以保持持久的登录状态。
-----
API这边不通过cookie判断用户是否登录，它只判断提交的api是否带有token，如果带有那么判断是否有效，有效则说明是登录的用户。

**Comment by hechuanhua** [comment]
@54sword 能加个QQ么，我这边服务端渲染的时候怎么老是获取不到cookie

**Comment by 54sword** [comment]
@hechuanhua 461616916
