### ISSUE TITLE
怎么配置才能在server端使用import和jsx语法

### ISSUE THREAD

**Issue by peytonCK** [54sword/xiaoduyu.com#24]
您好，一直疑惑怎么配置才能在server端使用Import和jsx语法。老是报：unexpected token import; 和renderToString <  的“<”也是unexpected token。

**Comment by 54sword** [comment]
创建一个js文件

```
require('babel-register');
require('babel-polyfill');

// 如下引入你的ES6语法的js文件
require('./server'); 
```
参考代码：https://github.com/54sword/xiaoduyu.com/blob/master/server/index.js
其他相关阅读：http://www.ruanyifeng.com/blog/2016/01/babel.html

**Comment by peytonCK** [comment]
@54sword   非常感谢。我之前在一个文件里用了两种模块引入方法：
`require('babel-register');
require('babel-polyfill');
import {
	counter,
	incCounter
} from './lib'
console.log(counter)

incCounter();
console.log(counter)`

这样报错，看了你的回答后，才明白，在一个文件里只能用一种模块引入方法。感谢。
