### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by yuanyongjun** [54sword/xiaoduyu.com#34]
![image](https://user-images.githubusercontent.com/17974972/33299894-a50d21b4-d428-11e7-90c0-f9689fcee7eb.png)

**Comment by yuanyongjun** [comment]
请问这个怎么解决

**Comment by 54sword** [comment]
不支持Windows系统下运行

**Comment by yuanyongjun** [comment]
额。。。没有解决方案吗

**Comment by 54sword** [comment]
在NODE_ENV前面增加set
如：set NODE_ENV
http://www.cnblogs.com/guizi/archive/2012/09/07/2674436.html
------------------------
我没有在windows下测试过，因此不保证windows上能运行，建议是mac或linux下运行
