### ISSUE TITLE
关注后，在个人首页中查找没有

### ISSUE THREAD

**Issue by yuanyongjun** [54sword/xiaoduyu.com#35]
![image](https://user-images.githubusercontent.com/17974972/33301077-a726b266-d42e-11e7-8fd9-91a3f81b021d.png)

**Comment by yuanyongjun** [comment]
![image](https://user-images.githubusercontent.com/17974972/33301103-ce9d9a58-d42e-11e7-8d66-ddc99ca90211.png)

**Comment by 54sword** [comment]
请刷新一下试一试，是否有最新关注的人。
感觉是在客户端，没有更新关注列表的问题，我已记录这个问题，感谢反馈哈。

**Comment by yuanyongjun** [comment]
嗯，刷新后是可以的
